name: Backend CI (E2E Checkout)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          docker compose up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/healthz \
              && curl -s http://localhost:8081/healthz \
              && curl -s http://localhost:8082/healthz \
              && curl -s http://localhost:8083/healthz; then
              echo "All services are up"
              exit 0
            fi
            sleep 5
          done
          echo "Services failed to start"
          docker compose logs
          exit 1

      - name: Run Full E2E Checkout Flow
        run: |
          go run ./tools/e2e_checkout/full_flow.go

      - name: Dump logs on failure
        if: failure()
        run: |
          docker compose logs

      - name: Shutdown services
        if: always()
        run: |
          docker compose down -v
